package com.ms.sw.Dto.user;

/**
 * {@code UserLoginResponse} is an immutable Data Transfer Object (DTO)
 * designed to carry the necessary information back to the client upon a
 * successful authentication (login).
 * <p>This DTO typically includes a confirmation message and the security token
 * (e.g., JWT) that the client must use for all later authorized requests.
 * @param message A success message confirming successful authentication (e.g., "Login successful").
 * @param token The security token (e.g., JSON Web Token) generated by the server,
 * required for accessing protected resources.
 * @see com.ms.sw.Dto.user.UserLoginRequest
 */
public record UserLoginResponse(String message, String token) {
}
